language: python
python:
  - "3.6.5"
  - "3.7-dev"
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - pip install -U setuptools
  - pip install poetry
  - poetry install
script:
  - make test
