version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "10101:27017"
    volumes:
      - /tmp/fastlane/mongo:/data/db
  redis:
    image: redis
    ports:
      - "10100:6379"
    volumes:
      - /tmp/fastlane/redis:/data
  redis2:
    image: redis:3.2-alpine
    volumes:
      - /tmp/fastlane/redis2:/data
    ports:
      - "10102:6379"
  redis-sentinel:
    build:
      context: ./redis-sentinel
    volumes:
      - /tmp/fastlane/redis-sentinel:/data
    links:
      - redis2
    ports:
      - "10103:26379"
  docker-host:
    image: docker:stable-dind
    privileged: true
    ports:
      - "1234:2375"
