version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27355:27017"
    volumes:
      - mongo-test-data:/data/db
  redis:
    image: redis
    volumes:
      - redis-test-data:/data
  docker-host:
    image: docker:stable-dind
    privileged: true
  fastlane:
    image: heynemann/fastlane:latest
    ports:
      - "10000:10000"
    env_file:
      - docker-compose-func-tests.env
    depends_on:
      - mongo
      - redis
      - docker-host

volumes:
  redis-test-data:
  mongo-test-data:
