site_name: fastlane
repo_url: https://github.com/heynemann/fastlane/
pages:
  - 'Home': index.md
  - 'Getting Started': 
    - 'The First 5 Minutes': getting-started.md
    - 'How To': how-to.md
    - 'Job Payload': job-payload.md
  - 'Configuration':
    - 'Installing and Running': install.md
  - 'Reference':
    - 'Executors': executors.md
    - 'Architecture and Design': architecture.md
    - 'API/Workers': api.md
extra_css:
  - custom.css
