site_name: fastlane
repo_url: https://github.com/heynemann/fastlane/

nav:
  - 'Home': index.md
  - 'Getting Started': getting-started.md
  - 'Installing and Running': install.md
  - 'Job Payload': job-payload.md
  - 'How To': how-to.md
  - 'Executors': executors.md
  - 'Architecture and Design': architecture.md
  - 'API/Workers': api.md

extra_css:
  - custom.css
